OPERATORS = "/operators"
COMMON_URL = "/tasks"
PRIORITIES = "/priorities"
STATUSES = "/statuses"
TYPES = "/types"
GRADES = "/grades"
SKILLS = "/skills"
TASK_COMMON_URL = "/tasks"
CONDITION = "/conditions"
DEFINE = "/define"
DISTRIBUTION = "/distribution"
CANCELED = "/cancelled"
COMPLETED = "/completed"
ACCEPTE='/accept_task'
CHANGE_PRIORITY='/change_priority'

LOGIC = "Логические"
DATE = "Даты"
ARITHMETIC = "Арифметические"
SPEC_SYMBOL = "$"

IN_QUEUE_ID = 6
EXECUTE_ID = 3

BEGIN_TIME_WORK = 9
END_TIME_WORK = 18
LEVEL_STEP = 0.2
LEVEL_START = 1
HOUR_IN_SECONDS = 3600

TASK_DURATION_RATIO = 0.05
SKILL_RATIO = 0.1
GO_DURATION_RATIO = 0.2
GRADE_RATIO = 0.3
PRIORITY_RATIO = 0.35

STATUS_ID_CANCELLED = 2
STATUS_ID_COMPLETED = 1
STATUS_ID_ACCEPTED = 4
STATUS_ID_APPOINTED = 3

DELIVERY_CARD_TYPE_ID = 3

PRIORITY_ID_VERY_HIGH = 4

MAX_VALUE_FEEDBACK=5
MIN_VALUE_FEEDBACK=1
