version: "3.6"

services:
  front:
    image: vaynbaum/task-hack:front
    container_name: front
    restart: always
    networks:
      - microservices
    ports:
      - 4200:4200

  proxy_service:
    image: vaynbaum/task-hack:proxy_service
    container_name: proxy_service
    volumes:
      - ./ng/nginx.conf:/etc/nginx.conf
    networks:
      - microservices
    ports:
      - 80:80

  redis_service:
    image: redis:latest
    container_name: redis_service
    networks:
      - microservices
    ports:
      - "6379:6379"
    expose:
      - 6379

  api_service:
    image: vaynbaum/task-hack:api_service
    container_name: api_service
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - redis_service
    networks:
      - microservices

  mailer_service:
    image: vaynbaum/task-hack:mailer_service
    container_name: mailer_service
    restart: always
    env_file:
      - mail.env
    ports:
      - "8002:8002"
    expose:
      - 8002
    networks:
      - microservices

  upload_file_service:
    image: vaynbaum/task-hack:upload_file_service
    container_name: upload_file_service
    restart: always
    env_file:
      - uf.env
    ports:
      - "8005:8005"
    expose:
      - 8005
    networks:
      - microservices

  celery_service:
    image: vaynbaum/task-hack:celery_service
    container_name: celery_service
    restart: always
    env_file:
      - .env
    depends_on:
      - redis_service
    networks:
      - microservices

  beat_service:
    image: vaynbaum/task-hack:beat_service
    container_name: beat_service
    restart: always
    env_file:
      - .env
    depends_on:
      - redis_service
    networks:
      - microservices

  flower_service:
    image: vaynbaum/task-hack:flower_service
    container_name: flower_service
    restart: always
    env_file:
      - .env
    depends_on:
      - redis_service
      - celery_service
      - beat_service
    networks:
      - microservices
    ports:
      - 5555:5555

networks:
  microservices:
    driver: bridge
