OFFICES_NOT_FOUND = "Объекты не найдены"
OFFICE_NOT_FOUND = "Объект не найден"
OFFICE_DELETE_SUCCESS = "Объект успешно удален!"
OFFICE_DELETE_FAILED = "Ошибка удаления объекта"
OFFICE_ADD_SUCCESS = "Объект успешно добавлен!"
OFFICE_ADD_FAILED = "Ошибка добавления объекта"
OFFICE_UPDATE_SUCCESS = "Объект успешно обновлен!"
OFFICE_UPDATE_FAILED = "Ошибка обновления объекта"

METHOD_WEIGHT_SUCCESS = "Расчет весов прошел успешно!"