ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 8

AUTH = "auth"
PATH_SIGNIN = "/signin"

ACCESS_TOKEN = "access_token"
REFRESH_TOKEN = "refresh_token"
TOKEN_TYPE_BEARER = "Bearer"
PAYLOAD_NAME_SCOPE = "scope"
PAYLOAD_NAME_EXPIRES = "exp"
PAYLOAD_NAME_ISSUEDAT = "iat"
PAYLOAD_NAME_SUB_ID = "sub_id"
PAYLOAD_NAME_SUB_ROLE_ID = "sub_role_id"
