OBJECTS_NOT_FOUND = "Объекты не найдены"
OBJECT_NOT_FOUND = "Объект не найден"
OBJECT_DELETE_SUCCESS = "Объект успешно удален!"
OBJECT_DELETE_FAILED = "Ошибка удаления объекта"
OBJECT_ADD_SUCCESS = "Объект успешно добавлен!"
OBJECT_ADD_FAILED = "Ошибка добавления объекта"
OBJECT_UPDATE_SUCCESS = "Объект успешно обновлен!"
OBJECT_UPDATE_FAILED = "Ошибка обновления объекта"